---
title: "Lab2"
output: pdf_document
date: '2022-04-03'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r add libraries, echo = FALSE, warning=FALSE, message = FALSE}

library(tidyverse)
library(ggplot2)
library(stargazer)


```


```{r read data, echo = FALSE, message = FALSE, warning=FALSE}

#initial read. Skip lines with metadata
qns <- read.csv('./2019_queens.csv', skip = 4)
bk <- read.csv('./2019_brooklyn.csv', skip = 4)
bx <- read.csv('./2019_bronx.csv', skip = 4)
mn <- read.csv('./2019_manhattan.csv', skip = 4)
si <- read.csv('./2019_statenisland.csv', skip = 4)
census <- read.csv('./ACSST5Y2019.S1903_data_with_overlays_2021-12-10T101330.csv', skip =1)

#combine borough-level df into single df
ls <- list(qns, bk, bx, mn, si)
df <- do.call("rbind", ls)


#Remove commas from numerical values and convert to numeric type
df$SALE.PRICE. <- as.numeric(gsub(",","",df$SALE.PRICE.))
df$GROSS.SQUARE.FEET. <- as.numeric(gsub(",","",df$GROSS.SQUARE.FEET.))

#parse and format zip code and median income from census data
incomes <- census %>%
  select(Geographic.Area.Name, names(census)[163]) %>%
  separate(col = Geographic.Area.Name, into = c('remove', 'zipcode'), sep = " ") %>%
  select(-1) %>%
  rename('median.income' = 2)  %>%
  lapply(as.integer)

#Left join sales data with income by zipcode
df <- rename(df, zipcode = ZIP.CODE.)
df <- merge(df, incomes, by = 'zipcode', all.x = TRUE)

# Filter for two-dwelling house and rename columns
df <- df %>%
  filter(BUILDING.CLASS.CATEGORY. == '02 TWO FAMILY DWELLINGS',
         SALE.PRICE. > 405000,
         GROSS.SQUARE.FEET. > 1120) %>%
  rename(c(sqft = GROSS.SQUARE.FEET., commercial.units = COMMERCIAL.UNITS., 
           boro = BOROUGH., sale.price = SALE.PRICE., block = BLOCK., lot = LOT.,
           address =ADDRESS., apt = APARTMENT.NUMBER. ))

#covert datatypes
df$commercial.units <- as.factor(df$commercial.units )
df$zipcode <- as.factor(df$zipcode)

#change Borough codes into Borough names
df$boro <- as.factor(plyr::mapvalues(df$boro,c(1,2,3,4,5), 
                                     c("Manhattan", "Bronx", "Brooklyn",  
                                       "Queens", "Staten Island") ))

#create age variable for further evaluation
df$age <- 2019 - df$YEAR.BUILT.

#Remove Easement variable which has all NA's. 
#Leaving this would create errors when dropping NA's across entire dataframe
df <- df %>% select(-8) 

#Remove NA's and duplicate values
df <- na.omit(df)
df <- df[!duplicated(df),]

#Split dataset 30% for EDA and remaining 70% for model testing
#for EDA
set.seed(12345)
samplesize <- round(nrow(df)*(.3))
df_EDA <- df[sample(nrow(df), size = samplesize, replace = FALSE), ]

#for modeling
df_test <- setdiff(df, df_EDA)
```

```{r, Exploratory Data Analysis Fig 3. and Fig 4.}
theme_set(theme(plot.title = element_text(hjust = 0.5), text = element_text(size=14)))

# overall distribution of sale price 

df_EDA %>% 
  ggplot(aes(x = sale.price))+
  geom_histogram(fill="#5297cc", colour='black') +
  ggtitle("Fig 3. Sale Price of Two-Family Dwellings")

df_EDA %>% 
  ggplot(aes(x = log(sale.price)))+
  geom_histogram(fill="#5297cc", colour='black') +
  ggtitle("Fig 4. Transformed Sale Price of Two-Family Dwellings")
```


```{r, Exploratory Data Analysis Fig 5 and Fig 6}
#price in commercial vs non commercial unit
df_EDA  %>% 
  ggplot(aes(x = log(sale.price), fill=commercial.units))+
  geom_histogram(bins = 30,  colour='black')+
  facet_grid(rows = vars(commercial.units))+
  labs(title = str_wrap("Fig 5. Sale Price of Two-Family Dwellings with and w/o Commercial Units", 60))

df_EDA %>%
  filter(commercial.units == 1) %>%
  ggplot(aes(x = log(sale.price)))+
  geom_histogram(bins = 30, fill='#00BFC4', colour='black') +
  labs(title = str_wrap("Fig 6. Sale Price of Two-Family Dwellings with Commercial Units in Manhattan", 60))

```




```{r, Exploratory Data Analysis Fig 4}
# Sale Price Distribution by borough
df_EDA %>% 
  ggplot(aes(x = log(sale.price)))+
  geom_histogram(fill="#5297cc", colour='black', bin=30)+
  facet_grid(rows = vars (boro), labeller = label_wrap_gen(width = 2, multi_line = TRUE))+
  ggtitle("Fig 7. Sale Prices of Two-Family Dwellings by Borough")

df_EDA %>%
  filter(boro == 'Manhattan') %>%
  ggplot(aes(x = log(sale.price)))+
  geom_histogram(bins = 30, fill='#5297cc', colour='black') +
  ggtitle("Fig 8. Sale Prices of Two-Family Dwellings in Manhattan")
```


```{r, Exploratory Data Analysis Fig 9, Fig 10 and Fig 11}
# % (log10) unit change sqft vs % change in sqft. facet by commercial vs non commercial unit

df_EDA %>% 
  ggplot(aes(x = sqft))+
  geom_histogram(fill="#5297cc", colour='black') +
  ggtitle("Fig 9. Distribution of Two-Family Dwellings Square footage")

df_EDA %>% 
  ggplot(aes(x = log(sqft)))+
  geom_histogram(fill="#5297cc", colour='black') +
  ggtitle("Fig 10. Transformed Distribution of Two-Family Dwellings of Square footage")

df_EDA %>%
  ggplot() + 
  aes(x =log(sqft), y =log(sale.price), color=commercial.units) +
  geom_jitter(alpha = 0.5) +
  facet_grid(rows = vars(commercial.units))+
  ggtitle("Fig 11. Sale Price of Two-Family Dwellings vs. Square Footage by Commercial Units")

```  

```{r, Exploratory Data Analysis Fig 12. and Fig 13.}
#distribution of age

df_EDA  %>% 
  ggplot(aes(x = (age)))+
  geom_histogram(fill="#5297cc", colour='black', bins="30")+
  ggtitle("Fig 12. Distribution of Two-Family Dwellings Property Age")

df_EDA %>%
  ggplot() + 
  aes(x = age, y =log(sale.price), color=commercial.units) +
  geom_point() +
  geom_jitter(alpha = 0.5) +
  labs(
    title = str_wrap("Fig 13. Age of Two-Family Dwellings vs Sale Price by Commercial Units", 60),
    color = 'Commercial units'
  )
```

```{r, Exploratory Data Analysis Fig 14}
#distribution of median income on log scale. The distribution is about the same
#so no transformation would be necessary
df_EDA  %>% 
  ggplot(aes(x = (median.income)))+
  geom_histogram(fill="#5297cc", colour='black', bin=30)+
  facet_grid(rows = vars (boro), labeller = label_wrap_gen(width = 2, multi_line = TRUE))+
  ggtitle("Fig 14. Distribution of Two-Family Dwellings Median Income per Borough")


df_EDA %>%
  filter(boro == 'Manhattan') %>%
  ggplot(aes(x = (median.income)))+
  geom_histogram(fill="#5297cc", colour='black', bin=30)+
  facet_grid(rows = vars (boro), labeller = label_wrap_gen(width = 2, multi_line = TRUE))+
  ggtitle("Fig 15. Distribution of Two-Family Dwellings Median Income in Manhattan")

```


**3. Modeling

***3.1 Base Model



$$sale\_price =  \beta_0 + \beta_1commecial\_units$$

***3.2 Second Model

$$sale\_price =  \beta_0 + \beta_1commecial\_units + \beta_2ln(square\_footage)$$
***3.3 Thrid Model
$$sale\_price =  \beta_0 + \beta_1commecial\_units + \beta_2ln(square\_footage) + \beta_3(property\_age)$$
***3.3 Fourth Model
$$sale\_price =  \beta_0 + \beta_1commecial\_units + \beta_2ln(square\_footage) + \beta_3(property\_age) + \beta_3(median\_income)$$

```{r results = "asis"}

model1 <- lm(log(sale.price) ~ commercial.units, data = df_test)
model2 <- lm(log(sale.price) ~ commercial.units + log(sqft), data = df_test)
model3 <- lm(log(sale.price) ~ commercial.units + log(sqft) + age, data = df_test)
model4 <- lm(log(sale.price) ~ commercial.units + log(sqft) + age + median.income, data = df_test)
model5 <- lm(log(sale.price) ~ commercial.units + log(sqft) + age + median.income + boro, data = df_test)

stargazer(
  model1, model2, model3, model4, model5,
    se = list(
    sqrt(diag(vcovHC(model1))),
    sqrt(diag(vcovHC(model2))),
    sqrt(diag(vcovHC(model3))),
    sqrt(diag(vcovHC(model4))),
    sqrt(diag(vcovHC(model5)))),
  type = 'text',
  title = 'Table 2. Summary of regression results'
)
```

```{r, test model1 and model2}
anova(model1, model2, test = 'F')
```

```{r, test model2 and model3}
anova(model2, model3, test = 'F')
```

```{r, test model3 and model4}
anova(model3, model4, test = 'F')
```

```{r, test model4 and model5}
anova(model4, model5, test = 'F')
```
plot(model5, which = 1)
plot(model5, which = 2)
plot(model5, which = 3)
plot(model5, which = 4)
df_test$res <- model5$residuals
```
